### ISSUE TITLE
Changing DF/nu parameter from default=3.0

### ISSUE THREAD

**Issue by ConorCUIster** [hawk31/pyGPGO#12]
Hello hawk31,

I am probably making an obvious mistake, having unsuccessfully tried to change both the "df" and "nu=3.0" parameters in both 'acquisition.py' and 'tStudentProcess.py' files.

Can you quickly explain how I change this parameter? I would like to see the impact of differing DF on the expected improvement utility function.

Many thanks,
ConorC

**Comment by hawk31** [comment]
Hello @ConorCUIster 

It should be enough to set the parameter in the surrogate model itself. 

```python
from pyGPGO.surrogates import tStudentProcess
surr = tStudentProcess(covfunc, nu=3.0)
```

Can you provide a minimum working example of whatever does not work?

**Comment by ConorCUIster** [comment]
José,


Thank you for your reply.


I may be missing something, but I tried changing the nu/DF paramater in the class defintion & I couldn't get the output chart (showing the results of x6 iterations for both the unknown function estimated and the acquisition function) to change.


I created my own code using the nu/DF parameter as a user-defined input variable, which seems to work OK i.e. the variability around the points sampled increases, as nu/DF also increases (all else equal).


Conor

________________________________
