### ISSUE TITLE
[JOSS]: Test coverage

### ISSUE THREAD

**Issue by dfm** [hawk31/pyGPGO#8]
Another comment for the JOSS review: openjournals/joss-reviews#41

I'm a bit concerned about the test coverage. There are tests that are being run on Travis (this is great!) but, as far as I can tell, only three different options are being tested even though many options seem to be available. I'd love to see the coverage report and it might be worth putting some thought into a broader test suite.

**Comment by hawk31** [comment]
Thanks for your useful comments.

More unit tests have been included under the `tests` folder. They extensively cover:

* Surrogates
* Kernels
* Acquisitions

Integration tests are taken care of by `test_GPGO`. While it is certainly very difficult to cover every single different combination of choices, this should give a much better starting point. 

Code coverage is now computed in the Travis build as well, and a badge is available on the README.md file.

Let me know if I can close this.

**Comment by dfm** [comment]
Looks good but, if you look at the coverage report, it looks like only the test coverage is counted. Make sure that you're actually measuring coverage across the module.

Also: it looks like you've added the `dist` and `*.egg-info` directories to the repo - you probably didn't mean to do that!

**Comment by hawk31** [comment]
Whoops, my fault.

I'm having some issues with Travis and pytest-cov reporting different estimates than a local installation. In the meantime I'm uploading the latter so that you can check.

**Comment by dfm** [comment]
Great! This looks better now.
